---
name: Setup
description: Setup Node.js and install dependencies.

inputs:
  node_version:
    description: The Node.js version.
    required: false
    default: '18'
  registry_url:
    description: The Node.js package registry URL.
    required: false
    default: https://registry.npmjs.org
  install_dependencies:
    description: Install dependencies.
    type: boolean
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      if: inputs.install_dependencies
      with:
        cache: npm
        node-version: ${{ inputs.node_version }}
        registry-url: ${{ inputs.registry_url }}
    - name: Setup Node.js without cache
      uses: actions/setup-node@v3
      if: '!inputs.install_dependencies'
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: ${{ inputs.registry_url }}
    - name: Install dependencies
      if: inputs.install_dependencies
      shell: bash
      run: npm ci
