---
name: Publish version

run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - v*

jobs:
  artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: npm pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          if-no-files-found: error
          path: '*.tgz'
  release:
    name: GitHub Releases
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}
          path: .
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          fail_on_unmatched_files: true
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: '*.tgz'
  npm:
    name: npm
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          install_dependencies: 'false'
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}
          path: .
      - name: Get meta
        id: meta
        run: |
          tgz=$(ls *.tgz | head -n1)
          echo "tgz=${tgz}" >> $GITHUB_OUTPUT
      - name: Publish
        uses: rxfork/npm-publish@v1
        with:
          access: public
          target: ${{ steps.meta.outputs.tgz }}
          token: ${{ secrets.NPM_TOKEN }}
  github:
    name: GitHub Packages
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      packages: write
    needs: artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          install_dependencies: 'false'
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}
          path: .
      - name: Get meta
        id: meta
        run: |
          tgz=$(ls *.tgz | head -n1)
          echo "tgz=${tgz}" >> $GITHUB_OUTPUT
      - name: Publish
        uses: rxfork/npm-publish@v1
        with:
          access: public
          target: ${{ steps.meta.outputs.tgz }}
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com
