---
name: publish

on:
  push:
    tags:
      - v*

jobs:
  npm:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
  github:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com
