---
name: publish

on:
  push:
    tags:
      - v*

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - name: Check published version
        id: published-version
        run: echo "::set-output name=view::$(npm view $(jq -r '.name' package.json)@$(jq -r '.version' package.json))"
      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Node modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Publish
        if: steps.published-version.outputs.view == ''
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
      - name: Check published version
        id: published-version
        run: echo "::set-output name=view::$(npm view $(jq -r '.name' package.json)@$(jq -r '.version' package.json))"
      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Node modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Publish
        run: npm publish --access public
        if: steps.published-version.outputs.view == ''
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
